import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/components/Providers";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className={cn("bg-white text-slate-900 antialiased", inter.className)}
      lang="en"
    >
      <body className="min-h-screen bg-slate-50 dark:bg-slate-900">
        <Providers>
          {children}
          <Navbar />
        </Providers>
      </body>
    </html>
  );
}
